{{- range .Values.applications }}
{{- $config := $.Values.config -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "example.%s" .name | quote }}
  namespace: argocd-gitops
spec:
  destination:
    namespace: argocd-gitops
    server: {{ $config.spec.destination.server | quote }}
  project: default
  sources: []
  source:
    path: {{ .path | default .name | quote }}
    repoURL: {{ $config.spec.source.repoURL }}
    targetRevision: {{ $config.spec.source.targetRevision }}
    {{- with .tool }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    directory:
      recurse: true
  syncPolicy:
    automated: {}
---
{{ end -}}
