config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/seb131276/argocd-example-apps
      targetRevision: master

applications:
  - name: guestbook
  - name: helm-guestbook
    tool:
      helm:
        releaseName: helm-guestbook
